# Generated by Django 4.1 on 2022-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCancha", models.CharField(max_length=60)),
                ("parCancha", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreJugador", models.CharField(max_length=60)),
                ("edadJugador", models.CharField(max_length=60)),
                ("matriculaJugador", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("golpesIdaScore", models.IntegerField()),
                ("golpesVueltaScore", models.IntegerField()),
                ("golpesTotalesScore", models.IntegerField()),
                ("fechaScore", models.DateField()),
            ],
        ),
    ]
